### ISSUE TITLE
Unable to retrieve XML results

### ISSUE THREAD

**Issue by chrisspen** [cockroach/episoder#5] opened 2017-05-24 04:22 UTC
When I run `episoder update`, I just get a series of these errors:

```
tvdb_error: There was an error with the XML retrieved from thetvdb.com:
unclosed token: line 4075, column 18
First try emptying the cache folder at..
/tmp/tvdb_api-u1001
If this does not resolve the issue, please try again later. If the error persists, report a bug on
http://dbr.lighthouseapp.com/projects/13342-tvdb_api/overview

```

**Comment by cockroach** [comment] 2017-05-24 23:49
Indeed, this has been happening to me as well.

At the moment I'm unable to reproduce the error but I will keep an eye on this; for now I'll assume it's a temporary server-side issue with the tvdb API.

**Comment by chrisspen** [comment] 2017-05-24 23:57
It seems to be a combination of a lack of error handling in the underlying [tvdb_api](https://github.com/dbr/tvdb_api/issues/45) coupled with TVDB sometimes including HTML markup in their episode overview description tags. Unfortunately, those devs have decided it's not their problem, and won't be fixing it in tvdb_api.

**Comment by cockroach** [comment] 2017-05-25 00:00
Thanks for the link, that does look unfortunate.

Do you have a show where this happens reliably so that I could try and find a workaround?

**Comment by chrisspen** [comment] 2017-05-25 00:03
Yeah, it's happening reliably with "It's Always Sunny in Philadelphia" and "Rick and Morty".

**Comment by cockroach** [comment] 2017-05-25 00:06
Thank you

**Comment by cockroach** [comment] 2017-05-25 00:13
Hmm, interestingly this seems to be a different issue. If I look at the XML file that was transferred it is actually incomplete, i.e. it ends abruptly on line 1530.

You can see this if you try to fetch the XML file directly (episoder -d should tell you the URL, it depends on the API key that you use).

**Comment by cockroach** [comment] 2017-05-25 00:17
There's also the fact that [this API is deprecated](http://thetvdb.com/wiki/index.php?title=Programmers_API).

**Comment by cockroach** [comment] 2017-05-25 00:23
There seems to be a python library for the new API, I suppose I will be modifying episoder to use that one instead. I will let you know when I have something that can be tested.

**Comment by chrisspen** [comment] 2017-05-25 14:46
Interesting. Good to know.

**Comment by cockroach** [comment] 2017-05-27 14:12
There is a [new episoder branch that uses the SOAP API](https://github.com/cockroach/episoder/tree/tvdb-rest-api). It's highly unpolished at the moment (no caching etc.) but it might work.

Feel free to give it a try and report any issues you find.

**Comment by cockroach** [comment] 2017-06-02 11:34
The fix has been merged into the development branch and will be released soon.

**Closed** 2017-06-06 22:08 UTC
Labels: bug
